# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'URLSessionDemo' do
pod 'Alamofire', '~> 4.5.1'
pod 'AlamofireImage' , '3.3.1'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for URLSessionDemo

end
